# ArgoCD ApplicationSet - Infrastructure (Dev)
# k3d 로컬 클러스터용
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: external-services
            namespace: ecommerce
            chart: charts/external-services
            syncWave: "1"
          # Istio Configuration은 별도 Application으로 분리 (prune 비활성화 필요)
          # charts/istio는 설정만 관리, Control Plane은 istioctl로 설치
          # 참조: argocd/applications/dev/istio.yaml
          - name: monitoring
            namespace: monitoring
            chart: charts/monitoring
            syncWave: "3"
          - name: argo-rollouts
            namespace: argo-rollouts
            chart: charts/argo-rollouts
            syncWave: "4"

  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: '{{.name}}'
        app.kubernetes.io/env: dev
        app.kubernetes.io/managed-by: argocd-applicationset
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/GroomC4/c4ang-infra.git
        targetRevision: feature/scenario-test
        path: '{{.chart}}'
        helm:
          valueFiles:
            - values.yaml
            - ../../config/dev/{{.name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /data
