# ArgoCD ApplicationSet - Airflow (Prod)
# 데이터 파이프라인 오케스트레이션 - prod 환경 전용
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: airflow

  template:
    metadata:
      name: airflow
      namespace: argocd
      labels:
        app.kubernetes.io/component: airflow
        app.kubernetes.io/env: prod
      annotations:
        argocd.argoproj.io/sync-wave: "20"
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/GroomC4/c4ang-infra.git
        targetRevision: feature/tunning-production-enviroment
        path: charts/airflow
        helm:
          valueFiles:
            - values.yaml
            - ../../config/prod/airflow.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: airflow
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
