# ArgoCD Application - Namespaces
# 네임스페이스를 Istio injection 레이블과 함께 관리
# 파일명 00-으로 시작하여 다른 ApplicationSet보다 먼저 적용됨
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # 가장 먼저 실행 (음수로 우선순위 높임)
spec:
  project: default
  source:
    repoURL: https://github.com/GroomC4/c4ang-infra.git
    targetRevision: demo
    path: argocd/manifest
    directory:
      include: 'namespaces.yaml'  # namespaces.yaml만 포함
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # 이미 네임스페이스를 생성하므로 false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
