# ArgoCD ApplicationSet - Airflow
# 데이터 파이프라인 오케스트레이션
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          # local 환경은 AWS RDS 설정이 필요하여 비활성화
          # - env: local
          #   cluster: https://kubernetes.default.svc
          #   namespace: airflow
          - env: prod
            cluster: https://eks-cluster.region.eks.amazonaws.com
            namespace: airflow

  syncPolicy:
    applicationsSync: create-only  # 생성만 하고 이후 수동 변경 유지

  template:
    metadata:
      name: 'airflow-{{.env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: airflow
        app.kubernetes.io/env: '{{.env}}'
      annotations:
        argocd.argoproj.io/sync-wave: "20"
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/GroomC4/c4ang-infra.git
        targetRevision: feature/adding-db-schema-and-enhancement-external-service  # TODO: 개발 완료 후 HEAD로 복구
        path: charts/airflow
        helm:
          valueFiles:
            - values.yaml
            - ../../config/{{.env}}/airflow.yaml
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # CRD가 큰 경우 필요
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
