# ArgoCD ApplicationSet - Infrastructure Components
# 환경별로 인프라 컴포넌트를 자동 생성
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Matrix generator: 환경 x 컴포넌트
    - matrix:
        generators:
          # 환경 정의
          - list:
              elements:
                - env: dev
                  cluster: https://kubernetes.default.svc
                  clusterName: k3d-msa-quality-cluster
                  namespaceSuffix: ""
                - env: prod
                  cluster: https://kubernetes.default.svc
                  clusterName: eks-prod
                  namespaceSuffix: "-prod"

          # 인프라 컴포넌트 정의
          - list:
              elements:
                - name: external-services
                  namespace: ecommerce
                  chart: charts/external-services
                  syncWave: "1"  # 네임스페이스(-1) 이후 배포
                - name: monitoring
                  namespace: monitoring
                  chart: charts/monitoring
                  syncWave: "2"
                - name: istio
                  namespace: ecommerce
                  chart: charts/istio
                  syncWave: "3"  # Istio는 external-services 이후
                - name: argo-rollouts
                  namespace: argo-rollouts
                  chart: charts/argo-rollouts
                  syncWave: "4"

  syncPolicy:
    applicationsSync: create-update  # ApplicationSet 변경 시 Application도 업데이트

  template:
    metadata:
      name: '{{.name}}-{{.env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: '{{.name}}'
        app.kubernetes.io/env: '{{.env}}'
        app.kubernetes.io/managed-by: argocd-applicationset
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/GroomC4/c4ang-infra.git
        targetRevision: HEAD
        path: '{{.chart}}'
        helm:
          valueFiles:
            # 차트 기본값 + 환경별 오버라이드
            - values.yaml
            - ../../config/{{.env}}/{{.name}}.yaml
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}{{.namespaceSuffix}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      # 헬스 체크 무시 (선택적)
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /data
